export const USER_MIN_LENGH_NAME = 3;
export const USER_MAX_LENGH_NAME = 40;

export const SAVE_MIN_LENGH_NAME = 3;
export const SAVE_MAX_LENGH_NAME = 40;

export const MANAGERGLOBAL_MIN_LENGH_NAME = 3;
export const MANAGERGLOBAL_MAX_LENGH_NAME = 40;
export const MANAGERGLOBAL_MIN_AGE = 18;
export const MANAGERGLOBAL_MAX_AGE = 90;

export const PLAYERGLOBAL_PRIMARY_POSITION_RATING = 1.0;
export const PLAYERGLOBAL_SECONDARY_POSITION_RATING = 0.95;
export const PLAYERGLOBAL_MIN_LENGH_NAME = 3;
export const PLAYERGLOBAL_MAX_LENGH_NAME = 40;
export const PLAYERGLOBAL_MIN_AGE = 14;
export const PLAYERGLOBAL_MAX_AGE = 50;
export const PLAYERGLOBAL_MIN_OVERALL = 1;
export const PLAYERGLOBAL_MAX_OVERALL = 100;
export const PLAYERGLOBAL_MIN_PRIMARY_POSITIONS = 1;
export const PLAYERGLOBAL_MAX_PRIMARY_POSITIONS = 3;
export const PLAYERGLOBAL_MAX_SECONDARY_POSITIONS = 5;

export const TEAMGLOBAL_MIN_LENGH_NAME = 3;
export const TEAMGLOBAL_MAX_LENGH_NAME = 40;
export const TEAMGLOBAL_MIN_PLAYERSGLOBAL = 1;
export const TEAMGLOBAL_MAX_PLAYERSGLOBAL = 40;

export const COMPETITIONGLOBAL_MIN_LENGH_NAME = 3;
export const COMPETITIONGLOBAL_MAX_LENGH_NAME = 40;
export const COMPETITIONGLOBAL_MIN_LENGH_SEASON = 3;
export const COMPETITIONGLOBAL_MAX_LENGH_SEASON = 10;
