export const USER_MIN_LENGH_NAME = 3;
export const USER_MAX_LENGH_NAME = 40;

export const MANAGERGLOBAL_MIN_LENGH_NAME = 3;
export const MANAGERGLOBAL_MAX_LENGH_NAME = 40;
export const MANAGERGLOBAL_MIN_AGE = 18;
export const MANAGERGLOBAL_MAX_AGE = 90;
