import { MigrationInterface, QueryRunner } from 'typeorm';

export class InsertTableCountry1707507916187 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    queryRunner.query(`
        INSERT INTO public.country(name, srcImage) VALUES
        ('Afeganistão', 'afeganistão.png'),
        ('África do Sul', 'áfrica_do_sul.png'),
        ('Albânia', 'albânia.png'),
        ('Alemanha', 'alemanha.png'),
        ('Andorra', 'andorra.png'),
        ('Angola', 'angola.png'),
        ('Anguila', 'anguila.png'),
        ('Antígua e Barbuda', 'antígua_e_barbuda.png'),
        ('Arábia Saudita', 'arábia_saudita.png'),
        ('Argélia', 'argélia.png'),
        ('Argentina', 'argentina.png'),
        ('Armênia', 'armênia.png'),
        ('Aruba', 'aruba.png'),
        ('Austrália', 'austrália.png'),
        ('Áustria', 'áustria.png'),
        ('Azerbaijão', 'azerbaijão.png'),
        ('Bahamas', 'bahamas.png'),
        ('Bangladesh', 'bangladesh.png'),
        ('Barbados', 'barbados.png'),
        ('Barém', 'barém.png'),
        ('Bélgica', 'bélgica.png'),
        ('Belize', 'belize.png'),
        ('Benim', 'benim.png'),
        ('Bermudas ', 'bermudas_.png'),
        ('Bielorrússia', 'bielorrússia.png'),
        ('Bolívia', 'bolívia.png'),
        ('Bósnia e Herzegovina', 'bósnia_e_herzegovina.png'),
        ('Botsuana', 'botsuana.png'),
        ('Brasil', 'brasil.png'),
        ('Brunei', 'brunei.png'),
        ('Bulgária', 'bulgária.png'),
        ('Burquina Fasso', 'burquina_fasso.png'),
        ('Burundi', 'burundi.png'),
        ('Butão', 'butão.png'),
        ('Cabo Verde', 'cabo_verde.png'),
        ('Camarões', 'camarões.png'),
        ('Camboja', 'camboja.png'),
        ('Canadá', 'canadá.png'),
        ('Catar', 'catar.png'),
        ('Cazaquistão', 'cazaquistão.png'),
        ('Chade', 'chade.png'),
        ('Chile', 'chile.png'),
        ('China', 'china.png'),
        ('Chipre', 'chipre.png'),
        ('Colômbia', 'colômbia.png'),
        ('Comores', 'comores.png'),
        ('Congo', 'congo.png'),
        ('Coreia do Norte', 'coreia_do_norte.png'),
        ('Coreia do Sul', 'coreia_do_sul.png'),
        ('Costa do Marfim', 'costa_do_marfim.png'),
        ('Costa Rica', 'costa_rica.png'),
        ('Croácia', 'croácia.png'),
        ('Cuba', 'cuba.png'),
        ('Curaçau', 'curaçau.png'),
        ('Dinamarca', 'dinamarca.png'),
        ('Djibouti', 'djibouti.png'),
        ('Dominica', 'dominica.png'),
        ('Egito', 'egito.png'),
        ('El Salvador', 'el_salvador.png'),
        ('Emirados Árabes Unidos', 'emirados_árabes_unidos.png'),
        ('Equador', 'equador.png'),
        ('Eritreia', 'eritreia.png'),
        ('Escócia', 'escócia.png'),
        ('Eslováquia', 'eslováquia.png'),
        ('Eslovênia', 'eslovênia.png'),
        ('Espanha', 'espanha.png'),
        ('Essuatíni', 'essuatíni.png'),
        ('Estados Unidos', 'estados_unidos.png'),
        ('Estônia', 'estônia.png'),
        ('Etiópia', 'etiópia.png'),
        ('Fiji', 'fiji.png'),
        ('Filipinas', 'filipinas.png'),
        ('Finlândia', 'finlândia.png'),
        ('França', 'frança.png'),
        ('Gabão', 'gabão.png'),
        ('Gâmbia', 'gâmbia.png'),
        ('Gana', 'gana.png'),
        ('Geórgia', 'geórgia.png'),
        ('Gibraltar', 'gibraltar.png'),
        ('Granada', 'granada.png'),
        ('Grécia', 'grécia.png'),
        ('Guam', 'guam.png'),
        ('Guatemala', 'guatemala.png'),
        ('Guiana', 'guiana.png'),
        ('Guiné Equatorial', 'guiné_equatorial.png'),
        ('Guiné', 'guiné.png'),
        ('Guiné-Bissau', 'guiné-bissau.png'),
        ('Haiti', 'haiti.png'),
        ('Holanda', 'holanda.png'),
        ('Honduras', 'honduras.png'),
        ('Hong Kong', 'hong_kong.png'),
        ('Hungria', 'hungria.png'),
        ('Iêmen', 'iêmen.png'),
        ('Ilhas Caimã', 'ilhas_caimã.png'),
        ('Ilhas Cook', 'ilhas_cook.png'),
        ('Ilhas Faroé', 'ilhas_faroé.png'),
        ('Ilhas Salomão', 'ilhas_salomão.png'),
        ('Ilhas Virgens Americanas', 'ilhas_virgens_americanas.png'),
        ('Ilhas Virgens Britânicas', 'ilhas_virgens_britânicas.png'),
        ('Índia', 'índia.png'),
        ('Indonésia', 'indonésia.png'),
        ('Inglaterra', 'inglaterra.png'),
        ('Irã', 'irã.png'),
        ('Iraque', 'iraque.png'),
        ('Irlanda do Norte', 'irlanda_do_norte.png'),
        ('Irlanda', 'irlanda.png'),
        ('Islândia', 'islândia.png'),
        ('Israel', 'israel.png'),
        ('Itália', 'itália.png'),
        ('Jamaica', 'jamaica.png'),
        ('Japão', 'japão.png'),
        ('Jordânia', 'jordânia.png'),
        ('Kosovo', 'kosovo.png'),
        ('Kuwait', 'kuwait.png'),
        ('Laos', 'laos.png'),
        ('Lesoto', 'lesoto.png'),
        ('Letônia', 'letônia.png'),
        ('Líbano', 'líbano.png'),
        ('Libéria', 'libéria.png'),
        ('Líbia', 'líbia.png'),
        ('Liechtenstein', 'liechtenstein.png'),
        ('Lituânia', 'lituânia.png'),
        ('Luxemburgo', 'luxemburgo.png'),
        ('Macau', 'macau.png'),
        ('Macedônia do Norte', 'macedônia_do_norte.png'),
        ('Madagascar', 'madagascar.png'),
        ('Malásia', 'malásia.png'),
        ('Malawi', 'malawi.png'),
        ('Maldivas', 'maldivas.png'),
        ('Mali', 'mali.png'),
        ('Malta', 'malta.png'),
        ('Marrocos', 'marrocos.png'),
        ('Maurícia', 'maurícia.png'),
        ('Mauritânia', 'mauritânia.png'),
        ('México', 'méxico.png'),
        ('Moldávia', 'moldávia.png'),
        ('Mongólia', 'mongólia.png'),
        ('Monserrate', 'monserrate.png'),
        ('Montenegro', 'montenegro.png'),
        ('Moçambique', 'moçambique.png'),
        ('Myanmar', 'myanmar.png'),
        ('Namíbia', 'namíbia.png'),
        ('Nepal', 'nepal.png'),
        ('Nicarágua', 'nicarágua.png'),
        ('Níger', 'níger.png'),
        ('Nigéria', 'nigéria.png'),
        ('Noruega', 'noruega.png'),
        ('Nova Caledônia', 'nova_caledônia.png'),
        ('Nova Zelândia', 'nova_zelândia.png'),
        ('Omã', 'omã.png'),
        ('País de Gales', 'país_de_gales.png'),
        ('Palestina', 'palestina.png'),
        ('Panamá', 'panamá.png'),
        ('Papua-Nova Guiné', 'papua-nova_guiné.png'),
        ('Paquistão', 'paquistão.png'),
        ('Paraguai', 'paraguai.png'),
        ('Peru', 'peru.png'),
        ('Polônia', 'polônia.png'),
        ('Porto Rico', 'porto_rico.png'),
        ('Portugal', 'portugal.png'),
        ('Quênia', 'quênia.png'),
        ('Quirguistão', 'quirguistão.png'),
        ('República Centro-Africana', 'república_centro-africana.png'),
        ('República Democrática do Congo', 'república_democrática_do_congo.png'),
        ('República Dominicana', 'república_dominicana.png'),
        ('Romênia', 'romênia.png'),
        ('Ruanda', 'ruanda.png'),
        ('Rússia', 'rússia.png'),
        ('Samoa Americana', 'samoa_americana.png'),
        ('Samoa', 'samoa.png'),
        ('San Marino', 'san_marino.png'),
        ('Santa Lúcia', 'santa_lúcia.png'),
        ('São Cristóvão e Neves', 'são_cristóvão_e_neves.png'),
        ('São Tomé e Príncipe', 'são_tomé_e_príncipe.png'),
        ('São Vicente e Granadinas', 'são_vicente_e_granadinas.png'),
        ('Seicheles', 'seicheles.png'),
        ('Senegal', 'senegal.png'),
        ('Serra Leoa', 'serra_leoa.png'),
        ('Sérvia', 'sérvia.png'),
        ('Singapura', 'singapura.png'),
        ('Síria', 'síria.png'),
        ('Somália', 'somália.png'),
        ('Sri Lanka', 'sri_lanka.png'),
        ('Sudão do Sul', 'sudão_do_sul.png'),
        ('Sudão', 'sudão.png'),
        ('Suécia', 'suécia.png'),
        ('Suíça', 'suíça.png'),
        ('Suriname', 'suriname.png'),
        ('Tailândia', 'tailândia.png'),
        ('Taipé Chinês', 'taipé_chinês.png'),
        ('Taiti', 'taiti.png'),
        ('Tajiquistão', 'tajiquistão.png'),
        ('Tanzânia', 'tanzânia.png'),
        ('Tchéquia', 'tchéquia.png'),
        ('Timor-Leste', 'timor-leste.png'),
        ('Togo', 'togo.png'),
        ('Tonga', 'tonga.png'),
        ('Trindade e Tobago', 'trindade_e_tobago.png'),
        ('Tunísia', 'tunísia.png'),
        ('Turcas e Caicos', 'turcas_e_caicos.png'),
        ('Turcomenistão', 'turcomenistão.png'),
        ('Turquia', 'turquia.png'),
        ('Ucrânia', 'ucrânia.png'),
        ('Uganda', 'uganda.png'),
        ('Uruguai', 'uruguai.png'),
        ('Uzbequistão', 'uzbequistão.png'),
        ('Vanuatu', 'vanuatu.png'),
        ('Venezuela', 'venezuela.png'),
        ('Vietnã', 'vietnã.png'),
        ('Zâmbia', 'zâmbia.png'),
        ('Zimbábue', 'zimbábue.png');
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    queryRunner.query(`
        DELETE FROM public.country;
    `);
  }
}
